#!/bin/bash -e

DATADIR="/var/lib/app-name-app"

# Create a group for the app if it isn't already there
if ! getent group "app-name" >/dev/null; then
	# Adding system group for the app: app-name.
	addgroup --system "app-name" >/dev/null
fi

# Create a user for the app if it isn't already there
if ! getent passwd app-name >/dev/null; then
	# Adding system user: mysql.
	adduser \
	  --system \
	  --disabled-login \
	  --ingroup app-name \
	  --home $DATADIR \
	  --gecos "app-name Rails app" \
	  --shell /bin/bash \
	  app-name  >/dev/null
fi

# Create the app's home dir, if it isn't there already...
if [ ! -d $DATADIR -a ! -L $DATADIR ]; then
 	mkdir -p $DATADIR
fi

# Fix ownership of the app's home dir...
# The "set +e" is necessary as e.g. a ".journal" of a ext3 partition is
# not chgrp'able (#318435). [nicked from mysql-server 5's pre-inst]
set +e
chown app-name:app-name $DATADIR
find $DATADIR -follow -not -group "app-name" -print0 2>/dev/null \
  | xargs -0 --no-run-if-empty chgrp "app-name"
set -e
